from django.contrib import admin
from .models import Character, NPCharacter, Monster, Spell, \
    Appearance, Getsup, BodyFeatures, Personality, \
    Background, Habit, Belongings, Features, Weapon, FirstName, LastName, \
    NPCJob, Misfortune, Mission, NPCAim, Weakness, Asset, Method, Secret, \
    Fame, Hobby, Relationship, Divinity, Result, \
    MonsterType, MonsterBodyFeature, MonsterFeature, MonsterAbility, \
    MonsterTactics, MonsterWeakness, MaterialEffect, MaterialElement, \
    MaterialForm, SpiritualEffect, SpiritualElement, SpiritualForm, Mutation, \
    Madness, MagicalDisaster, Book, Potion, MagicMaterial, \
    TreasureFeature, PreciousMaterial, Stuff, CityTopic, CityEvent, \
    AreaTopic, HighClassBuilding, DownstreamBuilding, CityAction, \
    BuildingRoom, StreetTactic, BuildingTactic, Faction, FactionFeature, \
    FactionAim, WildArea, WildTerrain, WildArtifact, WildAreaFeature, WildDiscovery, WildAction, WildThreat, \
    Herb, ToxicPlant, MotelNamePrefix, MotelNameSuffix, MotelUniqueness, \
    DungeonEntrance, DungeonForm, DungeonPlacement, WhyDungeonWasAbandoned, \
    DungeonReward, DungeonAction, DungeonRoom, DungeonRoomDetail, \
    DungeonMechanism, DungeonThreat, TrapEffect, TrapActuation              


admin.site.register(Character)
admin.site.register(NPCharacter)
admin.site.register(Monster)
admin.site.register(Spell)
admin.site.register(Appearance)
admin.site.register(Getsup)
admin.site.register(BodyFeatures)
admin.site.register(Personality)
admin.site.register(Background)
admin.site.register(Habit)
admin.site.register(Belongings)
admin.site.register(Features)
admin.site.register(Weapon)
admin.site.register(FirstName)
admin.site.register(LastName)
admin.site.register(NPCJob)
admin.site.register(Misfortune)
admin.site.register(Mission)
admin.site.register(NPCAim)
admin.site.register(Asset)
admin.site.register(Method)
admin.site.register(Secret)
admin.site.register(Fame)
admin.site.register(Hobby)
admin.site.register(Relationship)
admin.site.register(Divinity)
admin.site.register(Result)
admin.site.register(MonsterType)
admin.site.register(MonsterBodyFeature)
admin.site.register(MonsterFeature)
admin.site.register(MonsterAbility)
admin.site.register(MonsterTactics)
admin.site.register(MonsterWeakness)
admin.site.register(MaterialEffect)
admin.site.register(MaterialElement)
admin.site.register(MaterialForm)
admin.site.register(SpiritualEffect)
admin.site.register(SpiritualElement)
admin.site.register(SpiritualForm)
admin.site.register(Mutation)
admin.site.register(Madness)
admin.site.register(MagicalDisaster)
admin.site.register(Book)
admin.site.register(Potion)
admin.site.register(MagicMaterial)
admin.site.register(TreasureFeature)
admin.site.register(PreciousMaterial)
admin.site.register(Stuff)
admin.site.register(CityTopic)
admin.site.register(CityEvent)
admin.site.register(AreaTopic)
admin.site.register(HighClassBuilding)
admin.site.register(DownstreamBuilding)
admin.site.register(CityAction)
admin.site.register(BuildingRoom)
admin.site.register(StreetTactic)
admin.site.register(BuildingTactic)
admin.site.register(Faction)
admin.site.register(FactionFeature)
admin.site.register(FactionAim)
admin.site.register(Weakness)
admin.site.register(WildArea)
admin.site.register(WildTerrain)
admin.site.register(WildArtifact)
admin.site.register(WildAreaFeature)
admin.site.register(WildDiscovery)
admin.site.register(WildAction)
admin.site.register(WildThreat)
admin.site.register(Herb)
admin.site.register(ToxicPlant)
admin.site.register(MotelNamePrefix)
admin.site.register(MotelNameSuffix)
admin.site.register(MotelUniqueness)
admin.site.register(DungeonEntrance)
admin.site.register(DungeonForm)
admin.site.register(DungeonPlacement)
admin.site.register(WhyDungeonWasAbandoned)
admin.site.register(DungeonReward)
admin.site.register(DungeonAction)
admin.site.register(DungeonRoom)
admin.site.register(DungeonRoomDetail)
admin.site.register(DungeonMechanism)
admin.site.register(DungeonThreat)
admin.site.register(TrapEffect)
admin.site.register(TrapActuation)
