# Generated by Django 2.2.6 on 2019-12-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0002_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_class', models.IntegerField()),
                ('name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Beloings',
            new_name='Belongings',
        ),
        migrations.RenameModel(
            old_name='Name',
            new_name='FirstName',
        ),
    ]
