# Generated by Django 2.2.6 on 2019-12-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0005_auto_20191205_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcharacter',
            name='job',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='npcharacter',
            name='personality',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='areatopic',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='asset',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='background',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='bodyfeatures',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='booktopics',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='buildingspace',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='buildingtactic',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='beloings',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='body_features',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='features',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='getsup',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='habit',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='cityaction',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='cityevent',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='citytopic',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='downstreambuilding',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='faction',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='factionaim',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='factionfeature',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='fame',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='features',
            name='bigword',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='features',
            name='smallword',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='firstname',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='getsup',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='habit',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='highclassbuilding',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='lastname',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='madness',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='magicaldisaster',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='magicmaterial',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='materialeffect',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='materialelement',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='materialform',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='method',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='misfortune',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='mission',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monster',
            name='ablity',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monster',
            name='body_features',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monster_type',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monster',
            name='personality',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monster',
            name='tactics',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monster',
            name='traits',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monster',
            name='weakness',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monsterability',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monsterbodyfeature',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monsterfeature',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monstertactics',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='monsterweakness',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcaim',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='aim',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='appearance',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='asset',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='body_features',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='divinity',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='fame',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='getsup',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='habit',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='hometown',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='method',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='misfortune',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='mission',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='relationship',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcharacter',
            name='weakness',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='npcjob',
            name='job',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='personality',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='potion',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='preciousmaterial',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='result',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='secret',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spell',
            name='madness',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spell',
            name='magical_disaster',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spell',
            name='material_effect',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spell',
            name='material_element',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spell',
            name='material_form',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spell',
            name='mutation',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spiritual_effect',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spiritual_elelment',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spiritual_form',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spiritualeffect',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spiritualelement',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='spiritualform',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='streettactic',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='treasurefeature',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='weakness',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='bigword',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='smallword',
            field=models.CharField(default='', max_length=40),
        ),
    ]
