# Generated by Django 2.2.6 on 2019-12-12 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0006_auto_20191211_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookTopics',
            new_name='Book',
        ),
    ]
