# Generated by Django 2.2.6 on 2019-12-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0007_auto_20191212_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DungeonEntrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DungeonForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DungeonMechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DungeonPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DungeonReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DungeonRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DungeonRoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DungeonThreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MotelNamePrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MotelNameSuffix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MotelUniqueness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ToxicPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TrapActuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TrapEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WhyDungeonWasAbandoned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WildAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WildArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WildAreaFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WildArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WildDiscovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WildTerrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WildThreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='BuildingSpace',
            new_name='BuildingRoom',
        ),
    ]
